### ISSUE TITLE
Запрос 1. Сделать список дней рождений ППС

### ISSUE THREAD

**Issue by Artmotor** [kontur32/lipers-simplex#8]
Необходимо сделать список дней рождений ППС по внешнему виду как запрос у учеников с фильтрами по работающим сотрудникам, уволенным, общественникам (неофициалам) и сортировкам на текущий календарный год, текущий учебный год, графами подсчетов дат общего, педагогического стажа и стажа работы в Лицее (чтобы выявить круглые даты).

**Comment by kontur32** [comment]
Закрыто в части дней рождений
